FROM slzcc/java:java-jdk-1.8.0.201
 
ENV JAVA_HOME=/usr/local/jdk \
    JAVA_BIN=/usr/local/jdk/bin \
    JRE_HOME=/usr/local/jdk/jre
 
ENV ZK_USER=zookeeper \
    ZK_DATA_DIR="/var/lib/zookeeper/data" \
    ZK_DATA_LOG_DIR="/var/lib/zookeeper/log" \
    ZK_LOG_DIR="/var/log/zookeeper"
 
ARG GPG_KEY=C823E3E5B12AF29C67F81976F5CECB3CB5E9BD2D
 
ARG ZK_DIST=zookeeper-3.4.14

USER root

RUN echo "Acquire::http::Proxy \"http://192.168.7.24:44551\";" > /etc/apt/apt.conf && \
    apt-get update && \
    apt-get install -y wget netcat-openbsd && \
    apt-get install -y fonts-baekmuk fonts-nanum language-pack-zh-hans && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean

ENV TZ="Asia/Shanghai" \
    LANG="zh_CN.utf8"

RUN http_proxy=192.168.7.24:44551 wget -qO- "http://www.apache.org/dist/zookeeper/$ZK_DIST/$ZK_DIST.tar.gz" | tar zx -C /opt 

RUN export GNUPGHOME="$(mktemp -d)" && \
    rm -rf "$GNUPGHOME" "$ZK_DIST.tar.gz" "$ZK_DIST.tar.gz.asc" && \
    ln -s /opt/$ZK_DIST /opt/zookeeper && \
    rm -rf /opt/zookeeper/CHANGES.txt \
           /opt/zookeeper/README.txt \
           /opt/zookeeper/NOTICE.txt \
           /opt/zookeeper/CHANGES.txt \
           /opt/zookeeper/README_packaging.txt \
           /opt/zookeeper/build.xml \
           /opt/zookeeper/config \
           /opt/zookeeper/contrib \
           /opt/zookeeper/dist-maven \
           /opt/zookeeper/docs \
           /opt/zookeeper/ivy.xml \
           /opt/zookeeper/ivysettings.xml \
           /opt/zookeeper/recipes \
           /opt/zookeeper/src \
           /opt/zookeeper/$ZK_DIST.jar.asc \
           /opt/zookeeper/$ZK_DIST.jar.md5 \
           /opt/zookeeper/$ZK_DIST.jar.sha1   && \
    apt-get autoremove -y wget  && \
    rm -rf /var/lib/apt/lists/*
 
COPY start-zookeeper /opt/zookeeper/bin/start-zookeeper
COPY zookeeper-ready /opt/zookeeper/bin/zookeeper-ready
 
RUN useradd $ZK_USER && \
    [ `id -u $ZK_USER` -eq 1000 ] && \
    [ `id -g $ZK_USER` -eq 1000 ] && \
    mkdir -p $ZK_DATA_DIR $ZK_DATA_LOG_DIR $ZK_LOG_DIR /usr/share/zookeeper /tmp/zookeeper /usr/etc/&& \
    chown -R "$ZK_USER:$ZK_USER" /opt/$ZK_DIST $ZK_DATA_DIR $ZK_LOG_DIR $ZK_DATA_LOG_DIR /tmp/zookeeper && \
    ln -s /opt/zookeeper/conf/ /usr/etc/zookeeper && \
    ln -s /opt/zookeeper/bin/* /usr/bin && \
    ln -s /opt/zookeeper/$ZK_DIST.jar /usr/share/zookeeper/ && \
    ln -s /opt/zookeeper/lib/* /usr/share/zookeeper

RUN echo "" > /etc/apt/apt.conf

COPY start-supervisord /start-supervisord

CMD ["/start-supervisord"]
